//! Build script for `mn-brush`: generate libmypaint's missing autotools output,
//! then compile the vendored C with `cc`.
//!
//! The v1.6.1 **git tag** we vendored ships neither `configure`'s `config.h`
//! nor the two headers `generate.py` derives from `brushsettings.json`. This
//! script writes all three into `OUT_DIR` (nothing is written back into
//! `vendor/`), which also means there is no Python on the build path — this
//! machine has none. See `vendor/PATCHES.md`.
//!
//! It emits one extra file the C build does not use: `settings_gen.rs`, the
//! Rust-side setting/input id tables. Generating both from the same JSON in the
//! same pass is the whole point — the ids **must** match the C enum order, and
//! a mismatch would not error, it would just apply `.myb` values to the wrong
//! settings and make every brush feel wrong.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

/// The .c files autotools lists in `LIBMYPAINT_SOURCES`.
const LIBMYPAINT_SOURCES: &[&str] = &[
    "brushmodes.c",
    "fifo.c",
    "helpers.c",
    "mypaint-mapping.c",
    "mypaint.c",
    "mypaint-brush.c",
    "mypaint-brush-settings.c",
    "mypaint-fixed-tiled-surface.c",
    "mypaint-matrix.c",
    "mypaint-symmetry.c",
    "mypaint-rectangle.c",
    "mypaint-surface.c",
    "mypaint-tiled-surface.c",
    "operationqueue.c",
    "rng-double.c",
    "tilemap.c",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let vendor = manifest.join("../../vendor/libmypaint");
    // `canonicalize` on Windows returns a `\\?\` extended-length path, which
    // w64devkit's gcc does not understand as an `-I` argument (it silently
    // fails to find any header in it). Strip the prefix back off.
    let vendor = match vendor.canonicalize() {
        Ok(c) => PathBuf::from(
            c.to_string_lossy()
                .strip_prefix(r"\\?\")
                .map(str::to_owned)
                .unwrap_or_else(|| c.to_string_lossy().into_owned()),
        ),
        Err(_) => vendor,
    };
    let json_path = vendor.join("brushsettings.json");

    println!("cargo:rerun-if-changed=csrc/mn_surface.c");
    println!("cargo:rerun-if-changed={}", json_path.display());
    for f in LIBMYPAINT_SOURCES {
        println!("cargo:rerun-if-changed={}", vendor.join(f).display());
    }

    let defs = Defs::load(&json_path);
    write_if_changed(&out.join("config.h"), &config_h());
    write_if_changed(
        &out.join("mypaint-brush-settings-gen.h"),
        &defs.public_header(),
    );
    write_if_changed(&out.join("brushsettings-gen.h"), &defs.internal_header());
    write_if_changed(&out.join("settings_gen.rs"), &defs.rust_tables());

    let mut build = cc::Build::new();
    build
        .include(&vendor)
        .include(&out)
        // Vendored C we never debug, and dab compositing is the hot path — a
        // debug-profile -O0 libmypaint makes the pen feel wrong.
        .opt_level(2)
        // Upstream is not warning-clean and we do not intend to fix it; the
        // `#pragma omp` lines in particular are deliberate no-ops without
        // -fopenmp (we never pass it: no OpenMP, single-threaded by contract).
        .warnings(false)
        .flag_if_supported("-Wno-unknown-pragmas")
        .flag_if_supported("-std=gnu11")
        .file(manifest.join("csrc/mn_surface.c"));
    for f in LIBMYPAINT_SOURCES {
        build.file(vendor.join(f));
    }
    build.compile("mypaint");
}

/// `configure`'s output, reduced to the handful of macros the sources read.
///
/// `HAVE_GETTEXT` is deliberately **not** defined, so `mypaint-brush-settings.c`
/// takes its no-i18n branch (`dgettext(D, S) -> (S)`). `MYPAINT_CONFIG_USE_GLIB
/// 0` drops GObject/introspection. `MYPAINT_CONFIG_USE_JSON 0` selects the
/// stubbed `mypaint_brush_from_string` (vendor/PATCHES.md).
fn config_h() -> String {
    "/* Generated by crates/brush/build.rs — replaces autotools' config.h. */\n\
     #ifndef MN_LIBMYPAINT_CONFIG_H\n\
     #define MN_LIBMYPAINT_CONFIG_H\n\
     \n\
     #define GETTEXT_PACKAGE \"libmypaint\"\n\
     #define LOCALEDIR \"\"\n\
     #define MYPAINT_CONFIG_USE_GLIB 0\n\
     #define MYPAINT_CONFIG_USE_JSON 0\n\
     \n\
     #endif /* MN_LIBMYPAINT_CONFIG_H */\n"
        .to_string()
}

struct Setting {
    internal_name: String,
    displayed_name: String,
    constant: bool,
    minimum: Option<String>,
    default: String,
    maximum: Option<String>,
    tooltip: String,
}

struct Input {
    id: String,
    hard_minimum: Option<String>,
    soft_minimum: String,
    normal: String,
    soft_maximum: String,
    hard_maximum: Option<String>,
    displayed_name: String,
    tooltip: String,
}

struct Defs {
    inputs: Vec<Input>,
    settings: Vec<Setting>,
    states: Vec<String>,
}

impl Defs {
    fn load(path: &Path) -> Defs {
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        let v: Value = serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));

        let inputs = v["inputs"]
            .as_array()
            .expect("brushsettings.json: 'inputs' must be an array")
            .iter()
            .map(|i| Input {
                id: string_at(i, "id"),
                hard_minimum: num_at(i, "hard_minimum"),
                soft_minimum: num_at(i, "soft_minimum").expect("soft_minimum"),
                normal: num_at(i, "normal").expect("normal"),
                soft_maximum: num_at(i, "soft_maximum").expect("soft_maximum"),
                hard_maximum: num_at(i, "hard_maximum"),
                displayed_name: string_at(i, "displayed_name"),
                tooltip: string_at(i, "tooltip"),
            })
            .collect();

        let settings = v["settings"]
            .as_array()
            .expect("brushsettings.json: 'settings' must be an array")
            .iter()
            .map(|s| Setting {
                internal_name: string_at(s, "internal_name"),
                displayed_name: string_at(s, "displayed_name"),
                constant: s["constant"].as_bool().unwrap_or(false),
                minimum: num_at(s, "minimum"),
                default: num_at(s, "default").expect("default"),
                maximum: num_at(s, "maximum"),
                tooltip: string_at(s, "tooltip"),
            })
            .collect();

        let states = v["states"]
            .as_array()
            .expect("brushsettings.json: 'states' must be an array")
            .iter()
            .map(|s| s.as_str().expect("state name").to_string())
            .collect();

        Defs {
            inputs,
            settings,
            states,
        }
    }

    /// `mypaint-brush-settings-gen.h`: the three public enums, in JSON order.
    fn public_header(&self) -> String {
        let mut s = String::from(
            "// DO NOT EDIT - autogenerated by crates/brush/build.rs\n\n\
             #ifndef MYPAINT_BRUSH_SETTINGS_GEN_H\n#define MYPAINT_BRUSH_SETTINGS_GEN_H\n",
        );
        s.push_str(&c_enum(
            "MyPaintBrushInput",
            "MYPAINT_BRUSH_INPUT_",
            "MYPAINT_BRUSH_INPUTS_COUNT",
            self.inputs.iter().map(|i| i.id.to_uppercase()),
        ));
        s.push('\n');
        s.push_str(&c_enum(
            "MyPaintBrushSetting",
            "MYPAINT_BRUSH_SETTING_",
            "MYPAINT_BRUSH_SETTINGS_COUNT",
            self.settings.iter().map(|x| x.internal_name.to_uppercase()),
        ));
        s.push('\n');
        s.push_str(&c_enum(
            "MyPaintBrushState",
            "MYPAINT_BRUSH_STATE_",
            "MYPAINT_BRUSH_STATES_COUNT",
            self.states.iter().map(|x| x.to_uppercase()),
        ));
        s.push_str("\n#endif\n");
        s
    }

    /// `brushsettings-gen.h`: the static info arrays included by
    /// `mypaint-brush-settings.c` (which defines `N_` just above the include).
    fn internal_header(&self) -> String {
        let mut s = String::from(
            "// DO NOT EDIT - autogenerated by crates/brush/build.rs\n\n\
             #ifndef BRUSHSETTINGS_GEN_H\n#define BRUSHSETTINGS_GEN_H\n",
        );
        s.push_str("static MyPaintBrushSettingInfo settings_info_array[] = {\n");
        for x in &self.settings {
            let _ = writeln!(
                s,
                "    {{{}, N_({}), {}, {}, {}, {}, N_({})}},",
                c_str(&x.internal_name),
                c_str(&x.displayed_name),
                if x.constant { "TRUE" } else { "FALSE" },
                x.minimum.clone().unwrap_or_else(|| "-FLT_MAX".into()),
                x.default,
                x.maximum.clone().unwrap_or_else(|| "FLT_MAX".into()),
                c_str(&x.tooltip),
            );
        }
        s.push_str("};\n\nstatic MyPaintBrushInputInfo inputs_info_array[] = {\n");
        for x in &self.inputs {
            let _ = writeln!(
                s,
                "    {{{}, {}, {}, {}, {}, {}, N_({}), N_({})}},",
                c_str(&x.id),
                x.hard_minimum.clone().unwrap_or_else(|| "-FLT_MAX".into()),
                x.soft_minimum,
                x.normal,
                x.soft_maximum,
                x.hard_maximum.clone().unwrap_or_else(|| "FLT_MAX".into()),
                c_str(&x.displayed_name),
                c_str(&x.tooltip),
            );
        }
        s.push_str("};\n\n#endif\n");
        s
    }

    /// `settings_gen.rs`: the Rust half. Array index == C enum discriminant, by
    /// construction — both come from this one walk over `brushsettings.json`.
    fn rust_tables(&self) -> String {
        let mut s = String::from(
            "// DO NOT EDIT - autogenerated by crates/brush/build.rs from\n\
             // vendor/libmypaint/brushsettings.json. Index == the C enum value.\n\n",
        );

        let _ = writeln!(
            s,
            "/// Canonical setting names, in `MyPaintBrushSetting` order.\n\
             pub const SETTING_NAMES: [&str; {}] = [",
            self.settings.len()
        );
        for x in &self.settings {
            let _ = writeln!(s, "    {:?},", x.internal_name);
        }
        s.push_str("];\n\n");

        let _ = writeln!(
            s,
            "/// Canonical input names, in `MyPaintBrushInput` order.\n\
             pub const INPUT_NAMES: [&str; {}] = [",
            self.inputs.len()
        );
        for x in &self.inputs {
            let _ = writeln!(s, "    {:?},", x.id);
        }
        s.push_str("];\n\n");

        let _ = writeln!(
            s,
            "/// Stock default base value per setting, same order as `SETTING_NAMES`.\n\
             pub const SETTING_DEFAULTS: [f32; {}] = [",
            self.settings.len()
        );
        for x in &self.settings {
            let _ = writeln!(s, "    {}f32,", x.default);
        }
        s.push_str("];\n\n");

        s.push_str(
            "/// Setting ids. Named so a typo is a compile error, not a brush that\n\
             /// quietly feels wrong.\n#[allow(dead_code)]\npub mod setting {\n",
        );
        for (i, x) in self.settings.iter().enumerate() {
            let _ = writeln!(
                s,
                "    pub const {}: core::ffi::c_int = {i};",
                x.internal_name.to_uppercase()
            );
        }
        s.push_str("}\n\n/// Input ids.\n#[allow(dead_code)]\npub mod input {\n");
        for (i, x) in self.inputs.iter().enumerate() {
            let _ = writeln!(
                s,
                "    pub const {}: core::ffi::c_int = {i};",
                x.id.to_uppercase()
            );
        }
        s.push_str("}\n");
        s
    }
}

fn string_at(v: &Value, key: &str) -> String {
    v[key]
        .as_str()
        .unwrap_or_else(|| panic!("brushsettings.json: missing string {key} in {v}"))
        .to_string()
}

/// `null` means "unbounded" upstream and becomes `±FLT_MAX`; we keep the JSON
/// token text so `0.0` stays `0.0` and `2` stays `2` (both valid C floats).
fn num_at(v: &Value, key: &str) -> Option<String> {
    v.get(key).and_then(|n| n.as_f64().map(|_| n.to_string()))
}

fn c_enum(name: &str, prefix: &str, count: &str, items: impl Iterator<Item = String>) -> String {
    let mut s = String::from("typedef enum {\n");
    for it in items {
        let _ = writeln!(s, "    {prefix}{it},");
    }
    let _ = writeln!(s, "    {count}");
    let _ = writeln!(s, "}} {name};");
    s
}

/// C string literal. Upstream's generator escapes `"` and newlines; we also
/// escape backslashes, tabs and CR because `serde_json` hands us decoded text.
fn c_str(v: &str) -> String {
    let mut s = String::with_capacity(v.len() + 2);
    s.push('"');
    for c in v.chars() {
        match c {
            '\\' => s.push_str("\\\\"),
            '"' => s.push_str("\\\""),
            '\n' => s.push_str("\\n"),
            '\r' => s.push_str("\\r"),
            '\t' => s.push_str("\\t"),
            c => s.push(c),
        }
    }
    s.push('"');
    s
}

/// Avoid touching mtimes when nothing changed, so `cc` does not rebuild the
/// whole of libmypaint on every `cargo check`.
fn write_if_changed(path: &Path, contents: &str) {
    if std::fs::read_to_string(path).is_ok_and(|old| old == contents) {
        return;
    }
    std::fs::write(path, contents).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
}
