//! The CSP-derived presets (`assets/brushes/csp/`, generated by
//! `tools/cspmap.mjs`) and the two Tool-Property setters that go with them.
//!
//! Deliberately small. What is worth a test here is not "does libmypaint paint"
//! — `lib.rs` covers that — but the three conversion decisions that would be
//! silently wrong forever:
//!
//! 1. every generated file still loads (the generator emits shapes by hand);
//! 2. Real G-Pen inks at **constant alpha** while its width swings hugely with
//!    pressure. CSP says his pen modulates size only, and libmypaint's own
//!    defaults install a pressure→alpha ramp, so a preset that forgets to
//!    neutralise `opaque_multiply` looks right and feels wrong;
//! 3. `set_size_min_pct` actually moves the thin end of the stroke.

use std::path::{Path, PathBuf};

use mn_brush::settings::{input, setting};
use mn_brush::{BrushLibrary, MyBrush};
use mn_core::stabilize::CorrectCfg;
use mn_core::{Document, PenSample, StrokeSink, TILE_SIZE, TileIdx};
use mn_core::{Stabilizer, Taper};

const CSP_PRESETS: [&str; 9] = [
    "real-g-pen.myb",
    "real-g-pen-no-taper.myb",
    "milli-pen.myb",
    "pencil.myb",
    "crayon.myb",
    "eraser-hard.myb",
    "rough-wash.myb",
    "soft-airbrush.myb",
    "ink-gire-fude-pen.myb",
];

fn csp(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../assets/brushes/csp")
        .join(name)
}

fn classic(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../assets/brushes/classic")
        .join(name)
}

fn sample(x: f32, y: f32, p: f32, t: f64) -> PenSample {
    PenSample {
        x,
        y,
        pressure: p,
        tilt_x: 0.0,
        tilt_y: 0.0,
        t_ms: t,
    }
}

/// Horizontal stroke at constant pressure across the middle of a 512² canvas.
fn stroke(brush: &mut MyBrush, pressure: f32) -> Document {
    let mut doc = Document::new(512, 512);
    brush.begin(&mut doc);
    for i in 0..=60 {
        brush.sample(
            &mut doc,
            sample(100.0 + i as f32 * 5.0, 256.0, pressure, i as f64 * 8.0),
        );
    }
    brush.end(&mut doc);
    doc
}

/// Height in pixels of the painted band — i.e. the stroke's width.
fn stroke_width(doc: &Document) -> i32 {
    let (mut top, mut bottom) = (i32::MAX, i32::MIN);
    for (idx, tile) in doc.active_layer().tiles() {
        let (_, oy) = idx.origin();
        for y in 0..TILE_SIZE {
            if (0..TILE_SIZE).any(|x| tile.pixel(x, y)[3] > 0) {
                top = top.min(oy + y as i32);
                bottom = bottom.max(oy + y as i32);
            }
        }
    }
    if top > bottom { 0 } else { bottom - top + 1 }
}

/// Alpha at one canvas pixel, 0..32768 (fix15).
fn alpha_at(doc: &Document, x: i32, y: i32) -> u16 {
    doc.active_layer()
        .tile(TileIdx::of_pixel(x, y))
        .map(|t| t.pixel((x.rem_euclid(64)) as usize, (y.rem_euclid(64)) as usize)[3])
        .unwrap_or(0)
}

#[test]
fn every_csp_preset_loads() {
    for f in CSP_PRESETS {
        let b = MyBrush::load(&csp(f)).unwrap_or_else(|e| panic!("{f}: {e}"));
        assert!(
            b.radius_px() > 0.5,
            "{f}: radius {} px looks unset",
            b.radius_px()
        );
        assert!(b.base_opacity() > 0.0, "{f}: fully transparent");
    }

    // The Japanese display name survives an ASCII-safe file name, in the
    // loaded brush and in the picker listing alike.
    let ink = MyBrush::load(&csp("ink-gire-fude-pen.myb")).unwrap();
    assert_eq!(ink.name(), "インク切れ筆ペン");
    let listed = BrushLibrary::scan(&csp(""));
    // +1 for `dot-pen.myb` (row 96), which is NOT in `CSP_PRESETS`: it is a
    // hand-authored PROCEDURAL sub tool (`mn-engine: "dot"`) with no
    // libmypaint settings at all, so the per-preset load assertions above —
    // radius, opacity — have nothing to say about it. It is listed here so
    // the count still catches a file that goes missing.
    assert_eq!(listed.len(), CSP_PRESETS.len() + 1);
    assert!(listed.iter().any(|(n, _)| n == "Dot Pen"), "{listed:?}");
    assert!(
        listed.iter().any(|(n, _)| n == "インク切れ筆ペン"),
        "{listed:?}"
    );
    assert!(listed.iter().any(|(n, _)| n == "Real G-Pen"));
    // Presets without a "name" field still fall back to the file stem.
    assert_eq!(MyBrush::load(&classic("pen.myb")).unwrap().name(), "pen");
}

#[test]
fn real_g_pen_swings_width_but_not_alpha() {
    let g = || MyBrush::load(&csp("real-g-pen.myb")).unwrap();

    // Alpha must not follow pressure — neither directly nor through the
    // pressure→opaque_multiply ramp libmypaint installs by default.
    let b = g();
    assert_eq!(b.mapping_n(setting::OPAQUE, input::PRESSURE), 0);
    assert_eq!(b.mapping_n(setting::OPAQUE_MULTIPLY, input::PRESSURE), 0);
    assert_eq!(b.base_opacity(), 1.0);
    // 100 px in CSP is a radius of 50.
    assert!(
        (b.radius_px() - 50.0).abs() < 0.5,
        "radius {} px",
        b.radius_px()
    );
    assert!(
        (b.size_min_pct() - 3.0).abs() < 0.2,
        "min size {} %",
        b.size_min_pct()
    );

    let light = stroke(&mut g(), 0.15);
    let heavy = stroke(&mut g(), 0.9);
    let (lw, hw) = (stroke_width(&light), stroke_width(&heavy));
    assert!(
        hw as f32 / lw.max(1) as f32 > 3.0,
        "concave size curve should open up hard: {lw} px at 0.15, {hw} px at 0.9",
    );

    // Same ink at both pressures: sample the middle of the stroke, where the
    // dabs fully overlap in either case.
    let (la, ha) = (alpha_at(&light, 250, 256), alpha_at(&heavy, 250, 256));
    assert!(
        la > 30_000 && ha > 30_000,
        "stroke core is not opaque: {la} vs {ha}"
    );
    assert!(
        (la as f32 / ha as f32 - 1.0).abs() < 0.05,
        "alpha followed pressure: {la} at 0.15 vs {ha} at 0.9",
    );
}

#[test]
fn size_min_pct_moves_the_thin_end() {
    let mut b = MyBrush::load(&csp("real-g-pen.myb")).unwrap();

    b.set_size_min_pct(0.0);
    assert!(b.size_min_pct() < 1.5, "floor {} %", b.size_min_pct());
    let thin = stroke_width(&stroke(&mut b, 0.15));

    b.set_size_min_pct(50.0);
    assert!(
        (b.size_min_pct() - 50.0).abs() < 0.5,
        "floor {} %",
        b.size_min_pct()
    );
    let fat = stroke_width(&stroke(&mut b, 0.15));
    assert!(
        fat > thin * 2,
        "min-size 50 % should not draw like 0 %: {thin} vs {fat} px"
    );

    // Idempotent, and it must not have eaten the full-pressure width.
    let full = stroke_width(&stroke(&mut b, 1.0));
    b.set_size_min_pct(50.0);
    assert!((b.size_min_pct() - 50.0).abs() < 0.5);
    assert_eq!(stroke_width(&stroke(&mut b, 1.0)), full);
    assert_eq!(stroke_width(&stroke(&mut b, 0.15)), fat);
}

#[test]
fn size_min_pct_works_on_a_classic_preset_too() {
    // pen.myb maps pressure→radius as (0,0)→(1,0.5): full width at zero
    // pressure and wider above. That is the "minimum size is too high" bug in
    // preset form, so the setter has to survive it.
    let mut b = MyBrush::load(&classic("pen.myb")).unwrap();
    assert!(
        b.size_min_pct() > 50.0,
        "expected a fat floor, got {} %",
        b.size_min_pct()
    );

    let full_before = b.base_value(setting::RADIUS_LOGARITHMIC);
    b.set_size_min_pct(5.0);
    assert!(
        (b.size_min_pct() - 5.0).abs() < 0.5,
        "floor {} %",
        b.size_min_pct()
    );
    assert_eq!(
        b.base_value(setting::RADIUS_LOGARITHMIC),
        full_before,
        "base radius moved"
    );

    // Round-trip through the two setters that share the radius setting.
    b.set_size_multiplier(4.0);
    assert!(
        (b.size_min_pct() - 5.0).abs() < 0.5,
        "multiplier disturbed the floor"
    );
}

#[test]
fn base_opacity_round_trips_and_clamps() {
    let mut b = MyBrush::load(&csp("milli-pen.myb")).unwrap();
    assert!(
        (b.base_opacity() - 0.88).abs() < 1e-4,
        "CSP opacity 88 % should land as 0.88"
    );

    b.set_base_opacity(0.25);
    assert!((b.base_opacity() - 0.25).abs() < 1e-6);
    b.set_base_opacity(7.0);
    assert_eq!(b.base_opacity(), 1.0);
    b.set_base_opacity(f32::NAN);
    assert!(b.base_opacity().is_finite());
}

#[test]
fn randomization_round_trips_and_clears() {
    let mut b = MyBrush::load(&csp("real-g-pen.myb")).unwrap();
    assert_eq!(b.randomization().0, 0.0, "preset ships randomization off");

    // Amount only: flat value, no pressure mapping.
    b.set_randomization(0.4, 0.0, false);
    let (amt, min, abs) = b.randomization();
    assert!((amt - 0.4).abs() < 1e-5, "amount {amt}");
    assert!((min - 0.0).abs() < 1e-3, "min {min}");
    assert!(!abs);

    // With a floor: linear pressure curve, base pinned to 0.
    b.set_randomization(0.4, 25.0, false);
    let (amt, min, abs) = b.randomization();
    assert!((amt - 0.4).abs() < 1e-5, "amount {amt}");
    assert!((min - 25.0).abs() < 0.5, "min {min}");
    assert!(!abs);
    assert!(
        b.base_value(setting::RADIUS_BY_RANDOM).abs() < 1e-6,
        "curve lives in the mapping, not the base"
    );
    assert_eq!(b.mapping_n(setting::RADIUS_BY_RANDOM, input::PRESSURE), 2);

    // Zero clears both base and mapping — an untouched preset must stay
    // byte-identical to one that never heard of randomization.
    b.set_randomization(0.0, 0.0, false);
    assert_eq!(b.randomization(), (0.0, 0.0, false));
    assert_eq!(b.mapping_n(setting::RADIUS_BY_RANDOM, input::PRESSURE), 0);
}

#[test]
fn absolute_randomization_stays_finite_and_offcanvas_safe() {
    // The NaN guard exists because a bad radius corrupts the heap (round 6).
    // Absolute mode clamps instead of exp()'ing the noise, but the same
    // guarantee must hold — and the hook must not fire in stock mode.
    let mut b = MyBrush::load(&csp("milli-pen.myb")).unwrap();

    b.set_randomization(6.0, 0.0, true); // 6 px gaussian deviation
    let (amt, _, abs) = b.randomization();
    assert!(abs && (amt - 6.0).abs() < 1e-5);

    let doc = stroke(&mut b, 0.7);
    let w = stroke_width(&doc);
    // The assertion is about FINITENESS, not statistics (gaussian excursions
    // vary per run): a NaN radius would give garbage or absent bounds and
    // corrupt the heap (round 6). Width must exist…
    assert!(w > 2, "no visible paint at all (width {w})");
    // …and every painted tile must sit near the stroke line (y=256, tiles
    // 3..4; generous ±4 tiles ≈ ±256 px of excursion room).
    for idx in doc.active_layer().tiles().map(|(i, _)| i) {
        assert!((1..=8).contains(&idx.y), "garbage tile y {}", idx.y);
        assert!((0..=12).contains(&idx.x), "garbage tile x {}", idx.x);
    }

    // Stock mode: identical rng draws are impossible to assert, but the mode
    // flag must route through the stock path — readback says so.
    b.set_randomization(0.5, 0.0, false);
    assert!(!b.randomization().2);
}

// --- the correction stage, through the real chain --------------------------
//
// `stabilize.rs` proves the geometry on bare coordinates. These two prove the
// two things only the real `Stabilizer<Taper<MyBrush>>` can: that the stage is
// invisible at its defaults, and that turning it on moves actual pixels.

/// The app's brush chain, exactly as `App::new` builds it.
fn chain(preset: &str) -> Stabilizer<Taper<MyBrush>> {
    Stabilizer::new(Taper::new(MyBrush::load(&csp(preset)).unwrap()), 0.0)
}

/// Every painted pixel of a document, in a comparable order.
fn painted(doc: &Document) -> Vec<(i32, i32, [u16; 4])> {
    let mut v = Vec::new();
    for (idx, tile) in doc.active_layer().tiles() {
        let (ox, oy) = idx.origin();
        for y in 0..TILE_SIZE {
            for x in 0..TILE_SIZE {
                let px = tile.pixel(x, y);
                if px[3] > 0 {
                    v.push((ox + x as i32, oy + y as i32, px));
                }
            }
        }
    }
    v.sort_by_key(|(x, y, _)| (*y, *x));
    v
}

/// The same horizontal stroke as `stroke`, through any sink.
fn stroke_through<S: StrokeSink>(sink: &mut S, pressure: f32) -> Document {
    let mut doc = Document::new(512, 512);
    sink.begin(&mut doc);
    for i in 0..=60 {
        sink.sample(
            &mut doc,
            sample(100.0 + i as f32 * 5.0, 256.0, pressure, i as f64 * 8.0),
        );
    }
    sink.end(&mut doc);
    doc
}

/// A straight line with a ±3 px tremor riding on it.
fn wobbly_stroke<S: StrokeSink>(sink: &mut S) -> Document {
    let mut doc = Document::new(512, 512);
    sink.begin(&mut doc);
    for i in 0..=120 {
        let y = 256.0 + if (i / 3) % 2 == 0 { 3.0 } else { -3.0 };
        sink.sample(
            &mut doc,
            sample(100.0 + i as f32 * 2.0, y, 0.7, i as f64 * 8.0),
        );
    }
    sink.end(&mut doc);
    doc
}

/// The promise this round ships on: a sub tool saved before the Correction
/// group existed paints the SAME PIXELS it did. Not "looks similar" — the
/// same premultiplied bytes as the bare engine with no correction stage in
/// front of it at all. If anyone ever gives one of these dials a non-zero
/// default, this is what says so.
#[test]
fn the_correction_stage_is_invisible_at_its_defaults() {
    let mut bare = MyBrush::load(&csp("real-g-pen.myb")).unwrap();
    let plain = stroke(&mut bare, 0.7);

    let mut c = chain("real-g-pen.myb");
    c.set_correction(CorrectCfg::default());
    c.set_zoom(1.0);
    let corrected = stroke_through(&mut c, 0.7);

    let (a, b) = (painted(&plain), painted(&corrected));
    assert!(!a.is_empty(), "the control stroke painted nothing");
    assert_eq!(a, b, "the default correction stage changed the ink");
}

/// …and with post correction turned up, the tremor stops reaching the paper.
/// A wobbling line paints a band as tall as the brush PLUS the wobble; a
/// corrected one paints a band as tall as the brush.
#[test]
fn post_correction_narrows_a_wobbling_line() {
    let mut raw = chain("real-g-pen.myb");
    raw.set_zoom(1.0);
    let wide = stroke_width(&wobbly_stroke(&mut raw));

    let mut fixed = chain("real-g-pen.myb");
    fixed.set_correction(CorrectCfg {
        post: 1.0,
        ..Default::default()
    });
    fixed.set_zoom(1.0);
    let narrow = stroke_width(&wobbly_stroke(&mut fixed));

    assert!(wide > 6, "the wobble should be visible at all (got {wide})");
    assert!(
        narrow + 3 <= wide,
        "post correction should flatten the tremor: {narrow} vs {wide}"
    );
}
